//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest")
#ifdef RESTRICT_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest
#define INCLUDE_ALL_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest 0
#else
#define INCLUDE_ALL_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest 1
#endif
#undef RESTRICT_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest

#if !defined (DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_) && (INCLUDE_ALL_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest || defined(INCLUDE_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest))
#define DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_

#define RESTRICT_DeGreenrobotEventTestAbstractEventBusTest 1
#define INCLUDE_DeGreenrobotEventTestAbstractEventBusTest 1
#include "DeGreenrobotEventTestAbstractEventBusTest.h"

@class DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber;
@protocol JavaUtilList;

@interface DeGreenrobotEventTestEventBusOrderedSubscriptionsTest : DeGreenrobotEventTestAbstractEventBusTest {
 @public
  jint lastPrio_;
  id<JavaUtilList> registered_;
}

#pragma mark Public

- (instancetype)init;

- (void)testOrdered;

- (void)testOrderedBackgroundThread;

- (void)testOrderedBackgroundThreadSticky;

- (void)testOrderedMainThread;

- (void)testOrderedMainThreadSticky;

- (void)testOrderedSticky;

#pragma mark Protected

- (DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber *)register__WithInt:(jint)priority
                                                                                withBoolean:(jboolean)sticky;

- (void)runTestOrderedWithId:(id)event
                 withBoolean:(jboolean)sticky;

@end

J2OBJC_EMPTY_STATIC_INIT(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest)

J2OBJC_FIELD_SETTER(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest, registered_, id<JavaUtilList>)

FOUNDATION_EXPORT void DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_init(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *self);

FOUNDATION_EXPORT DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *new_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *create_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_init();

J2OBJC_TYPE_LITERAL_HEADER(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest)

#endif

#if !defined (DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber_) && (INCLUDE_ALL_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest || defined(INCLUDE_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber))
#define DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber_

@class DeGreenrobotEventTestEventBusOrderedSubscriptionsTest;
@class DeGreenrobotEventTestIntTestEvent;
@class JavaLangInteger;

@interface DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber : NSObject {
 @public
  jint prio_;
}

#pragma mark Public

- (instancetype)initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest:(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *)outer$
                                                                      withInt:(jint)prio;

- (void)onEventWithNSString:(NSString *)event;

- (void)onEventBackgroundThreadWithJavaLangInteger:(JavaLangInteger *)event;

- (void)onEventMainThreadWithDeGreenrobotEventTestIntTestEvent:(DeGreenrobotEventTestIntTestEvent *)event;

#pragma mark Protected

- (void)handleEventWithId:(id)event;

@end

J2OBJC_EMPTY_STATIC_INIT(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber)

FOUNDATION_EXPORT void DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber_initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_withInt_(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber *self, DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *outer$, jint prio);

FOUNDATION_EXPORT DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber *new_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber_initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_withInt_(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *outer$, jint prio) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber *create_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber_initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_withInt_(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *outer$, jint prio);

J2OBJC_TYPE_LITERAL_HEADER(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber)

#endif

#pragma pop_macro("INCLUDE_ALL_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest")
