//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DeGreenrobotEventTestEventBusStickyEventTest")
#ifdef RESTRICT_DeGreenrobotEventTestEventBusStickyEventTest
#define INCLUDE_ALL_DeGreenrobotEventTestEventBusStickyEventTest 0
#else
#define INCLUDE_ALL_DeGreenrobotEventTestEventBusStickyEventTest 1
#endif
#undef RESTRICT_DeGreenrobotEventTestEventBusStickyEventTest

#if !defined (DeGreenrobotEventTestEventBusStickyEventTest_) && (INCLUDE_ALL_DeGreenrobotEventTestEventBusStickyEventTest || defined(INCLUDE_DeGreenrobotEventTestEventBusStickyEventTest))
#define DeGreenrobotEventTestEventBusStickyEventTest_

#define RESTRICT_DeGreenrobotEventTestAbstractEventBusTest 1
#define INCLUDE_DeGreenrobotEventTestAbstractEventBusTest 1
#include "DeGreenrobotEventTestAbstractEventBusTest.h"

@class DeGreenrobotEventTestIntTestEvent;

@interface DeGreenrobotEventTestEventBusStickyEventTest : DeGreenrobotEventTestAbstractEventBusTest

#pragma mark Public

- (instancetype)init;

- (void)onEventWithDeGreenrobotEventTestIntTestEvent:(DeGreenrobotEventTestIntTestEvent *)event;

- (void)onEventWithNSString:(NSString *)event;

- (void)testPostNonStickyRegisterSticky;

- (void)testPostSticky;

- (void)testPostStickyAndGet;

- (void)testPostStickyRegisterNonSticky;

- (void)testPostStickyRemoveAll;

- (void)testPostStickyRemoveClass;

- (void)testPostStickyRemoveEvent;

- (void)testPostStickyThenPostNormal;

- (void)testPostStickyTwice;

- (void)testPostStickyTwoEvents;

- (void)testPostStickyWithRegisterAndUnregister;

- (void)testRemoveStickyEventInSubscriber;

@end

J2OBJC_EMPTY_STATIC_INIT(DeGreenrobotEventTestEventBusStickyEventTest)

FOUNDATION_EXPORT void DeGreenrobotEventTestEventBusStickyEventTest_init(DeGreenrobotEventTestEventBusStickyEventTest *self);

FOUNDATION_EXPORT DeGreenrobotEventTestEventBusStickyEventTest *new_DeGreenrobotEventTestEventBusStickyEventTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DeGreenrobotEventTestEventBusStickyEventTest *create_DeGreenrobotEventTestEventBusStickyEventTest_init();

J2OBJC_TYPE_LITERAL_HEADER(DeGreenrobotEventTestEventBusStickyEventTest)

#endif

#pragma pop_macro("INCLUDE_ALL_DeGreenrobotEventTestEventBusStickyEventTest")
