//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DeGreenrobotEventTestAbstractEventBusTest")
#ifdef RESTRICT_DeGreenrobotEventTestAbstractEventBusTest
#define INCLUDE_ALL_DeGreenrobotEventTestAbstractEventBusTest 0
#else
#define INCLUDE_ALL_DeGreenrobotEventTestAbstractEventBusTest 1
#endif
#undef RESTRICT_DeGreenrobotEventTestAbstractEventBusTest

#if !defined (DeGreenrobotEventTestAbstractEventBusTest_) && (INCLUDE_ALL_DeGreenrobotEventTestAbstractEventBusTest || defined(INCLUDE_DeGreenrobotEventTestAbstractEventBusTest))
#define DeGreenrobotEventTestAbstractEventBusTest_

#define RESTRICT_JunitFrameworkTestCase 1
#define INCLUDE_JunitFrameworkTestCase 1
#include "junit/framework/TestCase.h"

@class DeGreenrobotEventEventBus;
@class JavaLangThread;
@class JavaUtilConcurrentAtomicAtomicInteger;
@class JavaUtilConcurrentCountDownLatch;
@protocol JavaUtilList;

@interface DeGreenrobotEventTestAbstractEventBusTest : JunitFrameworkTestCase {
 @public
  DeGreenrobotEventEventBus *eventBus_;
  JavaUtilConcurrentAtomicAtomicInteger *eventCount_;
  id<JavaUtilList> eventsReceived_;
  volatile_id lastEvent_;
  volatile_id lastThread_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithBoolean:(jboolean)collectEventsReceived;

- (void)setUp;

#pragma mark Protected

- (void)assertEventCountWithInt:(jint)expectedEventCount;

- (void)awaitLatchWithJavaUtilConcurrentCountDownLatch:(JavaUtilConcurrentCountDownLatch *)latch
                                              withLong:(jlong)seconds;

- (void)countDownAndAwaitLatchWithJavaUtilConcurrentCountDownLatch:(JavaUtilConcurrentCountDownLatch *)latch
                                                          withLong:(jlong)seconds;

- (void)postInMainThreadWithId:(id)event;

- (void)trackEventWithId:(id)event;

- (void)waitForEventCountWithInt:(jint)expectedCount
                         withInt:(jint)maxMillis;

@end

J2OBJC_EMPTY_STATIC_INIT(DeGreenrobotEventTestAbstractEventBusTest)

J2OBJC_FIELD_SETTER(DeGreenrobotEventTestAbstractEventBusTest, eventBus_, DeGreenrobotEventEventBus *)
J2OBJC_FIELD_SETTER(DeGreenrobotEventTestAbstractEventBusTest, eventCount_, JavaUtilConcurrentAtomicAtomicInteger *)
J2OBJC_FIELD_SETTER(DeGreenrobotEventTestAbstractEventBusTest, eventsReceived_, id<JavaUtilList>)
J2OBJC_VOLATILE_FIELD_SETTER(DeGreenrobotEventTestAbstractEventBusTest, lastEvent_, id)
J2OBJC_VOLATILE_FIELD_SETTER(DeGreenrobotEventTestAbstractEventBusTest, lastThread_, JavaLangThread *)

inline jboolean DeGreenrobotEventTestAbstractEventBusTest_get_LONG_TESTS();
#define DeGreenrobotEventTestAbstractEventBusTest_LONG_TESTS false
J2OBJC_STATIC_FIELD_CONSTANT(DeGreenrobotEventTestAbstractEventBusTest, LONG_TESTS, jboolean)

FOUNDATION_EXPORT void DeGreenrobotEventTestAbstractEventBusTest_init(DeGreenrobotEventTestAbstractEventBusTest *self);

FOUNDATION_EXPORT void DeGreenrobotEventTestAbstractEventBusTest_initWithBoolean_(DeGreenrobotEventTestAbstractEventBusTest *self, jboolean collectEventsReceived);

J2OBJC_TYPE_LITERAL_HEADER(DeGreenrobotEventTestAbstractEventBusTest)

#endif

#if !defined (DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler_) && (INCLUDE_ALL_DeGreenrobotEventTestAbstractEventBusTest || defined(INCLUDE_DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler))
#define DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler_

#define RESTRICT_AndroidOsHandler 1
#define INCLUDE_AndroidOsHandler 1
#include "AndroidOsHandler.h"

@class AndroidOsLooper;
@class AndroidOsMessage;
@class DeGreenrobotEventTestAbstractEventBusTest;

@interface DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler : AndroidOsHandler

#pragma mark Public

- (instancetype)initWithDeGreenrobotEventTestAbstractEventBusTest:(DeGreenrobotEventTestAbstractEventBusTest *)outer$
                                              withAndroidOsLooper:(AndroidOsLooper *)looper;

- (void)handleMessageWithAndroidOsMessage:(AndroidOsMessage *)msg;

#pragma mark Package-Private

- (void)postWithId:(id)event;

@end

J2OBJC_EMPTY_STATIC_INIT(DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler)

FOUNDATION_EXPORT void DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler_initWithDeGreenrobotEventTestAbstractEventBusTest_withAndroidOsLooper_(DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler *self, DeGreenrobotEventTestAbstractEventBusTest *outer$, AndroidOsLooper *looper);

FOUNDATION_EXPORT DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler *new_DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler_initWithDeGreenrobotEventTestAbstractEventBusTest_withAndroidOsLooper_(DeGreenrobotEventTestAbstractEventBusTest *outer$, AndroidOsLooper *looper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler *create_DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler_initWithDeGreenrobotEventTestAbstractEventBusTest_withAndroidOsLooper_(DeGreenrobotEventTestAbstractEventBusTest *outer$, AndroidOsLooper *looper);

J2OBJC_TYPE_LITERAL_HEADER(DeGreenrobotEventTestAbstractEventBusTest_EventPostHandler)

#endif

#pragma pop_macro("INCLUDE_ALL_DeGreenrobotEventTestAbstractEventBusTest")
