//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DeGreenrobotEventTestIntTestEvent")
#ifdef RESTRICT_DeGreenrobotEventTestIntTestEvent
#define INCLUDE_ALL_DeGreenrobotEventTestIntTestEvent 0
#else
#define INCLUDE_ALL_DeGreenrobotEventTestIntTestEvent 1
#endif
#undef RESTRICT_DeGreenrobotEventTestIntTestEvent

#if !defined (DeGreenrobotEventTestIntTestEvent_) && (INCLUDE_ALL_DeGreenrobotEventTestIntTestEvent || defined(INCLUDE_DeGreenrobotEventTestIntTestEvent))
#define DeGreenrobotEventTestIntTestEvent_

@interface DeGreenrobotEventTestIntTestEvent : NSObject {
 @public
  jint value_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)value;

@end

J2OBJC_EMPTY_STATIC_INIT(DeGreenrobotEventTestIntTestEvent)

FOUNDATION_EXPORT void DeGreenrobotEventTestIntTestEvent_initWithInt_(DeGreenrobotEventTestIntTestEvent *self, jint value);

FOUNDATION_EXPORT DeGreenrobotEventTestIntTestEvent *new_DeGreenrobotEventTestIntTestEvent_initWithInt_(jint value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DeGreenrobotEventTestIntTestEvent *create_DeGreenrobotEventTestIntTestEvent_initWithInt_(jint value);

J2OBJC_TYPE_LITERAL_HEADER(DeGreenrobotEventTestIntTestEvent)

#endif

#pragma pop_macro("INCLUDE_ALL_DeGreenrobotEventTestIntTestEvent")
