//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "DeGreenrobotEventTestIntTestEvent.h"
#include "J2ObjC_source.h"

@implementation DeGreenrobotEventTestIntTestEvent

- (instancetype)initWithInt:(jint)value {
  DeGreenrobotEventTestIntTestEvent_initWithInt_(self, value);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "value_", "I", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "I" };
  static const J2ObjcClassInfo _DeGreenrobotEventTestIntTestEvent = { "IntTestEvent", "de.greenrobot.event.test", ptrTable, methods, fields, 7, 0x1, 1, 1, -1, -1, -1, -1, -1 };
  return &_DeGreenrobotEventTestIntTestEvent;
}

@end

void DeGreenrobotEventTestIntTestEvent_initWithInt_(DeGreenrobotEventTestIntTestEvent *self, jint value) {
  NSObject_init(self);
  self->value_ = value;
}

DeGreenrobotEventTestIntTestEvent *new_DeGreenrobotEventTestIntTestEvent_initWithInt_(jint value) {
  J2OBJC_NEW_IMPL(DeGreenrobotEventTestIntTestEvent, initWithInt_, value)
}

DeGreenrobotEventTestIntTestEvent *create_DeGreenrobotEventTestIntTestEvent_initWithInt_(jint value) {
  J2OBJC_CREATE_IMPL(DeGreenrobotEventTestIntTestEvent, initWithInt_, value)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DeGreenrobotEventTestIntTestEvent)
