//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "DeGreenrobotEventEventBus.h"
#include "DeGreenrobotEventEventBusException.h"
#include "DeGreenrobotEventTestAbstractEventBusTest.h"
#include "DeGreenrobotEventTestEventBusCancelEventDeliveryTest.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "java/util/concurrent/CountDownLatch.h"
#include "java/util/concurrent/atomic/AtomicInteger.h"
#include "junit/framework/TestCase.h"
#include "org/junit/Test.h"

@interface DeGreenrobotEventTestEventBusCancelEventDeliveryTest () {
 @public
  NSException *failed_;
}

@end

J2OBJC_FIELD_SETTER(DeGreenrobotEventTestEventBusCancelEventDeliveryTest, failed_, NSException *)

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$0();

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$1();

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$2();

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$3();

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$4();

@interface DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber () {
 @public
  DeGreenrobotEventTestEventBusCancelEventDeliveryTest *this$0_;
  jboolean cancel_;
}

@end

@interface DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent () {
 @public
  DeGreenrobotEventTestEventBusCancelEventDeliveryTest *this$0_;
}

@end

@interface DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread () {
 @public
  DeGreenrobotEventTestEventBusCancelEventDeliveryTest *this$0_;
}

@end

@implementation DeGreenrobotEventTestEventBusCancelEventDeliveryTest

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  DeGreenrobotEventTestEventBusCancelEventDeliveryTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)testCancel {
  DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber *canceler = create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_(self, true);
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) register__WithId:create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_(self, false)];
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) register__WithId:canceler withInt:1];
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) register__WithId:create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_(self, false)];
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) postWithId:@"42"];
  JunitFrameworkTestCase_assertEqualsWithInt_withInt_(1, [((JavaUtilConcurrentAtomicAtomicInteger *) nil_chk(eventCount_)) intValue]);
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) unregisterWithId:canceler];
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) postWithId:@"42"];
  JunitFrameworkTestCase_assertEqualsWithInt_withInt_(1 + 2, [eventCount_ intValue]);
}

- (void)testCancelInBetween {
  DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber *canceler = create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_(self, true);
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) register__WithId:canceler withInt:2];
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) register__WithId:create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_(self, false) withInt:1];
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) register__WithId:create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_(self, false) withInt:3];
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) postWithId:@"42"];
  JunitFrameworkTestCase_assertEqualsWithInt_withInt_(2, [((JavaUtilConcurrentAtomicAtomicInteger *) nil_chk(eventCount_)) intValue]);
}

- (void)testCancelOutsideEventHandler {
  @try {
    [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) cancelEventDeliveryWithId:self];
    JunitFrameworkTestCase_failWithNSString_(@"Should have thrown");
  }
  @catch (DeGreenrobotEventEventBusException *e) {
  }
}

- (void)testCancelWrongEvent {
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) register__WithId:create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_(self)];
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) postWithId:@"42"];
  JunitFrameworkTestCase_assertEqualsWithInt_withInt_(0, [((JavaUtilConcurrentAtomicAtomicInteger *) nil_chk(eventCount_)) intValue]);
  JunitFrameworkTestCase_assertNotNullWithId_(failed_);
}

- (void)testCancelInMainThread {
  DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread *subscriber = create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_(self);
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) register__WithId:subscriber];
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) postWithId:@"42"];
  [self awaitLatchWithJavaUtilConcurrentCountDownLatch:subscriber->done_ withLong:10];
  JunitFrameworkTestCase_assertEqualsWithInt_withInt_(0, [((JavaUtilConcurrentAtomicAtomicInteger *) nil_chk(eventCount_)) intValue]);
  JunitFrameworkTestCase_assertNotNullWithId_(failed_);
}

- (void)dealloc {
  RELEASE_(failed_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 0, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 2, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 3, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 4, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(testCancel);
  methods[2].selector = @selector(testCancelInBetween);
  methods[3].selector = @selector(testCancelOutsideEventHandler);
  methods[4].selector = @selector(testCancelWrongEvent);
  methods[5].selector = @selector(testCancelInMainThread);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "failed_", "LNSException;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { (void *)&DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$0, (void *)&DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$1, (void *)&DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$2, (void *)&DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$3, (void *)&DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$4, "LDeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber;LDeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent;LDeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread;" };
  static const J2ObjcClassInfo _DeGreenrobotEventTestEventBusCancelEventDeliveryTest = { "EventBusCancelEventDeliveryTest", "de.greenrobot.event.test", ptrTable, methods, fields, 7, 0x1, 6, 1, -1, 5, -1, -1, -1 };
  return &_DeGreenrobotEventTestEventBusCancelEventDeliveryTest;
}

@end

void DeGreenrobotEventTestEventBusCancelEventDeliveryTest_init(DeGreenrobotEventTestEventBusCancelEventDeliveryTest *self) {
  DeGreenrobotEventTestAbstractEventBusTest_init(self);
}

DeGreenrobotEventTestEventBusCancelEventDeliveryTest *new_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_init() {
  J2OBJC_NEW_IMPL(DeGreenrobotEventTestEventBusCancelEventDeliveryTest, init)
}

DeGreenrobotEventTestEventBusCancelEventDeliveryTest *create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_init() {
  J2OBJC_CREATE_IMPL(DeGreenrobotEventTestEventBusCancelEventDeliveryTest, init)
}

IOSObjectArray *DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$1() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$2() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$3() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *DeGreenrobotEventTestEventBusCancelEventDeliveryTest__Annotations$4() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DeGreenrobotEventTestEventBusCancelEventDeliveryTest)

@implementation DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber

- (instancetype)initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest:(DeGreenrobotEventTestEventBusCancelEventDeliveryTest *)outer$
                                                                 withBoolean:(jboolean)cancel {
  DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_(self, outer$, cancel);
  return self;
}

- (void)onEventWithNSString:(NSString *)event {
  [this$0_ trackEventWithId:event];
  if (cancel_) {
    [((DeGreenrobotEventEventBus *) nil_chk(this$0_->eventBus_)) cancelEventDeliveryWithId:event];
  }
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest:withBoolean:);
  methods[1].selector = @selector(onEventWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LDeGreenrobotEventTestEventBusCancelEventDeliveryTest;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "cancel_", "Z", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "Z", "onEvent", "LNSString;", "LDeGreenrobotEventTestEventBusCancelEventDeliveryTest;" };
  static const J2ObjcClassInfo _DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber = { "Subscriber", "de.greenrobot.event.test", ptrTable, methods, fields, 7, 0x0, 2, 2, 3, -1, -1, -1, -1 };
  return &_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber;
}

@end

void DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber *self, DeGreenrobotEventTestEventBusCancelEventDeliveryTest *outer$, jboolean cancel) {
  JreStrongAssign(&self->this$0_, outer$);
  NSObject_init(self);
  self->cancel_ = cancel;
}

DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber *new_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_(DeGreenrobotEventTestEventBusCancelEventDeliveryTest *outer$, jboolean cancel) {
  J2OBJC_NEW_IMPL(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber, initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_, outer$, cancel)
}

DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber *create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_(DeGreenrobotEventTestEventBusCancelEventDeliveryTest *outer$, jboolean cancel) {
  J2OBJC_CREATE_IMPL(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber, initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_withBoolean_, outer$, cancel)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_Subscriber)

@implementation DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent

- (instancetype)initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest:(DeGreenrobotEventTestEventBusCancelEventDeliveryTest *)outer$ {
  DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_(self, outer$);
  return self;
}

- (void)onEventWithNSString:(NSString *)event {
  @try {
    [((DeGreenrobotEventEventBus *) nil_chk(this$0_->eventBus_)) cancelEventDeliveryWithId:self];
  }
  @catch (DeGreenrobotEventEventBusException *e) {
    JreStrongAssign(&this$0_->failed_, e);
  }
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest:);
  methods[1].selector = @selector(onEventWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LDeGreenrobotEventTestEventBusCancelEventDeliveryTest;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "onEvent", "LNSString;", "LDeGreenrobotEventTestEventBusCancelEventDeliveryTest;" };
  static const J2ObjcClassInfo _DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent = { "SubscriberCancelOtherEvent", "de.greenrobot.event.test", ptrTable, methods, fields, 7, 0x0, 2, 1, 2, -1, -1, -1, -1 };
  return &_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent;
}

@end

void DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent *self, DeGreenrobotEventTestEventBusCancelEventDeliveryTest *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  NSObject_init(self);
}

DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent *new_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_(DeGreenrobotEventTestEventBusCancelEventDeliveryTest *outer$) {
  J2OBJC_NEW_IMPL(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent, initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_, outer$)
}

DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent *create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_(DeGreenrobotEventTestEventBusCancelEventDeliveryTest *outer$) {
  J2OBJC_CREATE_IMPL(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent, initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberCancelOtherEvent)

@implementation DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread

- (instancetype)initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest:(DeGreenrobotEventTestEventBusCancelEventDeliveryTest *)outer$ {
  DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_(self, outer$);
  return self;
}

- (void)onEventMainThreadWithNSString:(NSString *)event {
  @try {
    [((DeGreenrobotEventEventBus *) nil_chk(this$0_->eventBus_)) cancelEventDeliveryWithId:event];
  }
  @catch (DeGreenrobotEventEventBusException *e) {
    JreStrongAssign(&this$0_->failed_, e);
  }
  [((JavaUtilConcurrentCountDownLatch *) nil_chk(done_)) countDown];
}

- (void)dealloc {
  RELEASE_(this$0_);
  RELEASE_(done_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest:);
  methods[1].selector = @selector(onEventMainThreadWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LDeGreenrobotEventTestEventBusCancelEventDeliveryTest;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "done_", "LJavaUtilConcurrentCountDownLatch;", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "onEventMainThread", "LNSString;", "LDeGreenrobotEventTestEventBusCancelEventDeliveryTest;" };
  static const J2ObjcClassInfo _DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread = { "SubscriberMainThread", "de.greenrobot.event.test", ptrTable, methods, fields, 7, 0x0, 2, 2, 2, -1, -1, -1, -1 };
  return &_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread;
}

@end

void DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread *self, DeGreenrobotEventTestEventBusCancelEventDeliveryTest *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  NSObject_init(self);
  JreStrongAssignAndConsume(&self->done_, new_JavaUtilConcurrentCountDownLatch_initWithInt_(1));
}

DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread *new_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_(DeGreenrobotEventTestEventBusCancelEventDeliveryTest *outer$) {
  J2OBJC_NEW_IMPL(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread, initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_, outer$)
}

DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread *create_DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread_initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_(DeGreenrobotEventTestEventBusCancelEventDeliveryTest *outer$) {
  J2OBJC_CREATE_IMPL(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread, initWithDeGreenrobotEventTestEventBusCancelEventDeliveryTest_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DeGreenrobotEventTestEventBusCancelEventDeliveryTest_SubscriberMainThread)
