//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "DeGreenrobotEventEventBus.h"
#include "DeGreenrobotEventTestAbstractEventBusTest.h"
#include "DeGreenrobotEventTestEventBusOrderedSubscriptionsTest.h"
#include "DeGreenrobotEventTestIntTestEvent.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "android/util/Log.h"
#include "java/lang/Integer.h"
#include "java/lang/annotation/Annotation.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"
#include "junit/framework/TestCase.h"
#include "org/junit/Test.h"

@interface DeGreenrobotEventTestEventBusOrderedSubscriptionsTest () {
 @public
  NSString *fail_;
}

- (void)unregisterAll;

@end

J2OBJC_FIELD_SETTER(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest, fail_, NSString *)

__attribute__((unused)) static void DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_unregisterAll(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *self);

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$0();

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$1();

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$2();

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$3();

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$4();

__attribute__((unused)) static IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$5();

@interface DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber () {
 @public
  DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *this$0_;
}

@end

@implementation DeGreenrobotEventTestEventBusOrderedSubscriptionsTest

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)testOrdered {
  [self runTestOrderedWithId:@"42" withBoolean:false];
}

- (void)testOrderedMainThread {
  [self runTestOrderedWithId:create_DeGreenrobotEventTestIntTestEvent_initWithInt_(42) withBoolean:false];
}

- (void)testOrderedBackgroundThread {
  [self runTestOrderedWithId:JavaLangInteger_valueOfWithInt_(42) withBoolean:false];
}

- (void)testOrderedSticky {
  [self runTestOrderedWithId:@"42" withBoolean:true];
}

- (void)testOrderedMainThreadSticky {
  [self runTestOrderedWithId:create_DeGreenrobotEventTestIntTestEvent_initWithInt_(42) withBoolean:true];
}

- (void)testOrderedBackgroundThreadSticky {
  [self runTestOrderedWithId:JavaLangInteger_valueOfWithInt_(42) withBoolean:true];
}

- (void)runTestOrderedWithId:(id)event
                 withBoolean:(jboolean)sticky {
  [self register__WithInt:1 withBoolean:sticky];
  [self register__WithInt:-1 withBoolean:sticky];
  [self register__WithInt:10 withBoolean:sticky];
  [self register__WithInt:0 withBoolean:sticky];
  [self register__WithInt:-100 withBoolean:sticky];
  JunitFrameworkTestCase_assertEqualsWithInt_withInt_(5, [((id<JavaUtilList>) nil_chk(registered_)) size]);
  [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) postWithId:event];
  [self waitForEventCountWithInt:5 withInt:10000];
  JunitFrameworkTestCase_assertEqualsWithNSString_withNSString_(nil, fail_);
  DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_unregisterAll(self);
}

- (void)unregisterAll {
  DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_unregisterAll(self);
}

- (DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber *)register__WithInt:(jint)priority
                                                                                withBoolean:(jboolean)sticky {
  DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber *subscriber = create_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber_initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_withInt_(self, priority);
  if (sticky) {
    [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) registerStickyWithId:subscriber withInt:priority];
  }
  else {
    [((DeGreenrobotEventEventBus *) nil_chk(eventBus_)) register__WithId:subscriber withInt:priority];
  }
  [((id<JavaUtilList>) nil_chk(registered_)) addWithId:subscriber];
  return subscriber;
}

- (void)dealloc {
  RELEASE_(registered_);
  RELEASE_(fail_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 0, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 2, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 3, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 4, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, 5, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber;", 0x4, 8, 9, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(testOrdered);
  methods[2].selector = @selector(testOrderedMainThread);
  methods[3].selector = @selector(testOrderedBackgroundThread);
  methods[4].selector = @selector(testOrderedSticky);
  methods[5].selector = @selector(testOrderedMainThreadSticky);
  methods[6].selector = @selector(testOrderedBackgroundThreadSticky);
  methods[7].selector = @selector(runTestOrderedWithId:withBoolean:);
  methods[8].selector = @selector(unregisterAll);
  methods[9].selector = @selector(register__WithInt:withBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "lastPrio_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "registered_", "LJavaUtilList;", .constantValue.asLong = 0, 0x10, -1, -1, 10, -1 },
    { "fail_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { (void *)&DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$0, (void *)&DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$1, (void *)&DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$2, (void *)&DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$3, (void *)&DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$4, (void *)&DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$5, "runTestOrdered", "LNSObject;Z", "register", "IZ", "Ljava/util/List<Lde/greenrobot/event/test/EventBusOrderedSubscriptionsTest$PrioSubscriber;>;", "LDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber;" };
  static const J2ObjcClassInfo _DeGreenrobotEventTestEventBusOrderedSubscriptionsTest = { "EventBusOrderedSubscriptionsTest", "de.greenrobot.event.test", ptrTable, methods, fields, 7, 0x1, 10, 3, -1, 11, -1, -1, -1 };
  return &_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest;
}

@end

void DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_init(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *self) {
  DeGreenrobotEventTestAbstractEventBusTest_init(self);
  self->lastPrio_ = JavaLangInteger_MAX_VALUE;
  JreStrongAssignAndConsume(&self->registered_, new_JavaUtilArrayList_init());
}

DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *new_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_init() {
  J2OBJC_NEW_IMPL(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest, init)
}

DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *create_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_init() {
  J2OBJC_CREATE_IMPL(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest, init)
}

void DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_unregisterAll(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *self) {
  for (DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber * __strong subscriber in nil_chk(self->registered_)) {
    [((DeGreenrobotEventEventBus *) nil_chk(self->eventBus_)) unregisterWithId:subscriber];
  }
}

IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$1() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$2() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$3() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$4() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *DeGreenrobotEventTestEventBusOrderedSubscriptionsTest__Annotations$5() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_OrgJunitTest(OrgJunitTest_None_class_(), 0) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest)

@implementation DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber

- (instancetype)initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest:(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *)outer$
                                                                      withInt:(jint)prio {
  DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber_initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_withInt_(self, outer$, prio);
  return self;
}

- (void)onEventWithNSString:(NSString *)event {
  [self handleEventWithId:event];
}

- (void)onEventMainThreadWithDeGreenrobotEventTestIntTestEvent:(DeGreenrobotEventTestIntTestEvent *)event {
  [self handleEventWithId:event];
}

- (void)onEventBackgroundThreadWithJavaLangInteger:(JavaLangInteger *)event {
  [self handleEventWithId:event];
}

- (void)handleEventWithId:(id)event {
  if (prio_ > this$0_->lastPrio_) {
    JreStrongAssign(&this$0_->fail_, JreStrcat("$I$I", @"Called prio ", prio_, @" after ", this$0_->lastPrio_));
  }
  this$0_->lastPrio_ = prio_;
  AndroidUtilLog_dWithNSString_withNSString_(JreLoadStatic(DeGreenrobotEventEventBus, TAG), JreStrcat("$I$@", @"Subscriber ", prio_, @" got: ", event));
  [this$0_ trackEventWithId:event];
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 7, 8, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest:withInt:);
  methods[1].selector = @selector(onEventWithNSString:);
  methods[2].selector = @selector(onEventMainThreadWithDeGreenrobotEventTestIntTestEvent:);
  methods[3].selector = @selector(onEventBackgroundThreadWithJavaLangInteger:);
  methods[4].selector = @selector(handleEventWithId:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LDeGreenrobotEventTestEventBusOrderedSubscriptionsTest;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "prio_", "I", .constantValue.asLong = 0, 0x10, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "I", "onEvent", "LNSString;", "onEventMainThread", "LDeGreenrobotEventTestIntTestEvent;", "onEventBackgroundThread", "LJavaLangInteger;", "handleEvent", "LNSObject;", "LDeGreenrobotEventTestEventBusOrderedSubscriptionsTest;" };
  static const J2ObjcClassInfo _DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber = { "PrioSubscriber", "de.greenrobot.event.test", ptrTable, methods, fields, 7, 0x12, 5, 2, 9, -1, -1, -1, -1 };
  return &_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber;
}

@end

void DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber_initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_withInt_(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber *self, DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *outer$, jint prio) {
  JreStrongAssign(&self->this$0_, outer$);
  NSObject_init(self);
  self->prio_ = prio;
}

DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber *new_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber_initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_withInt_(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *outer$, jint prio) {
  J2OBJC_NEW_IMPL(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber, initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_withInt_, outer$, prio)
}

DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber *create_DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber_initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_withInt_(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest *outer$, jint prio) {
  J2OBJC_CREATE_IMPL(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber, initWithDeGreenrobotEventTestEventBusOrderedSubscriptionsTest_withInt_, outer$, prio)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DeGreenrobotEventTestEventBusOrderedSubscriptionsTest_PrioSubscriber)
