//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DeGreenrobotEventTestEventBusMainThreadTest")
#ifdef RESTRICT_DeGreenrobotEventTestEventBusMainThreadTest
#define INCLUDE_ALL_DeGreenrobotEventTestEventBusMainThreadTest 0
#else
#define INCLUDE_ALL_DeGreenrobotEventTestEventBusMainThreadTest 1
#endif
#undef RESTRICT_DeGreenrobotEventTestEventBusMainThreadTest

#if !defined (DeGreenrobotEventTestEventBusMainThreadTest_) && (INCLUDE_ALL_DeGreenrobotEventTestEventBusMainThreadTest || defined(INCLUDE_DeGreenrobotEventTestEventBusMainThreadTest))
#define DeGreenrobotEventTestEventBusMainThreadTest_

#define RESTRICT_DeGreenrobotEventTestAbstractEventBusTest 1
#define INCLUDE_DeGreenrobotEventTestAbstractEventBusTest 1
#include "DeGreenrobotEventTestAbstractEventBusTest.h"

@interface DeGreenrobotEventTestEventBusMainThreadTest : DeGreenrobotEventTestAbstractEventBusTest

#pragma mark Public

- (instancetype)init;

- (void)onEventMainThreadWithNSString:(NSString *)event;

- (void)setUp;

- (void)testPost;

- (void)testPostInBackgroundThread;

#pragma mark Protected

- (void)tearDown;

@end

J2OBJC_EMPTY_STATIC_INIT(DeGreenrobotEventTestEventBusMainThreadTest)

FOUNDATION_EXPORT void DeGreenrobotEventTestEventBusMainThreadTest_init(DeGreenrobotEventTestEventBusMainThreadTest *self);

FOUNDATION_EXPORT DeGreenrobotEventTestEventBusMainThreadTest *new_DeGreenrobotEventTestEventBusMainThreadTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DeGreenrobotEventTestEventBusMainThreadTest *create_DeGreenrobotEventTestEventBusMainThreadTest_init();

J2OBJC_TYPE_LITERAL_HEADER(DeGreenrobotEventTestEventBusMainThreadTest)

#endif

#if !defined (DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster_) && (INCLUDE_ALL_DeGreenrobotEventTestEventBusMainThreadTest || defined(INCLUDE_DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster))
#define DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster_

#define RESTRICT_JavaLangThread 1
#define INCLUDE_JavaLangThread 1
#include "java/lang/Thread.h"

@class DeGreenrobotEventTestEventBusMainThreadTest;

@interface DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster : JavaLangThread {
 @public
  volatile_jboolean running_;
}

#pragma mark Public

- (instancetype)initWithDeGreenrobotEventTestEventBusMainThreadTest:(DeGreenrobotEventTestEventBusMainThreadTest *)outer$;

- (void)run;

#pragma mark Package-Private

- (void)postWithId:(id)event;

- (void)shutdown;

@end

J2OBJC_EMPTY_STATIC_INIT(DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster)

FOUNDATION_EXPORT void DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster_initWithDeGreenrobotEventTestEventBusMainThreadTest_(DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster *self, DeGreenrobotEventTestEventBusMainThreadTest *outer$);

FOUNDATION_EXPORT DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster *new_DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster_initWithDeGreenrobotEventTestEventBusMainThreadTest_(DeGreenrobotEventTestEventBusMainThreadTest *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster *create_DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster_initWithDeGreenrobotEventTestEventBusMainThreadTest_(DeGreenrobotEventTestEventBusMainThreadTest *outer$);

J2OBJC_TYPE_LITERAL_HEADER(DeGreenrobotEventTestEventBusMainThreadTest_BackgroundPoster)

#endif

#pragma pop_macro("INCLUDE_ALL_DeGreenrobotEventTestEventBusMainThreadTest")
