//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_UiTester")
#ifdef RESTRICT_UiTester
#define INCLUDE_ALL_UiTester 0
#else
#define INCLUDE_ALL_UiTester 1
#endif
#undef RESTRICT_UiTester

#if !defined (UiTester_) && (INCLUDE_ALL_UiTester || defined(INCLUDE_UiTester))
#define UiTester_

@interface UiTester : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)runTests;

@end

J2OBJC_EMPTY_STATIC_INIT(UiTester)

FOUNDATION_EXPORT void UiTester_init(UiTester *self);

FOUNDATION_EXPORT UiTester *new_UiTester_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT UiTester *create_UiTester_init();

FOUNDATION_EXPORT void UiTester_runTests();

J2OBJC_TYPE_LITERAL_HEADER(UiTester)

#endif

#pragma pop_macro("INCLUDE_ALL_UiTester")
